title: "GraphArch Documentation"
title_separator: "-"
repository: "ekgf/grapharch"
source: .
destination: ./_site
collections_dir: .
url: "https://ekgf.github.com/grapharch"
# remote_theme: mmistakes/minimal-mistakes@4.26.2
remote_theme: pages-themes/midnight@v0.2.0
locale: "en-US"
show_downloads: false
gist:
  noscript: false
livereload: true
open_url: true
nav:
  - title: "Design Goals"
    url: "/design-goals"
  - title: "Features"
    url: "/feature"
  - title: "Contributing"
    url: "/contribute"

# Site Author
author:
  name             : "Jacobus Geluk"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "TODO"
  location         : "London, UK"
  links:
    - label: "EKGF"
      icon: "fas fa-fw fa-link"
      url: "https://ekgf.org"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ekgf/grapharch"

# Handling Reading
safe                : false
strict_front_matter : false
include:
  - .htaccess
  - pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "*.code-workspace"
  - "src/**"
  - "target/**"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - serve.sh
keep_files:
  - .git
encoding: UTF-8
markdown_ext: "md"

# Filtering Content
show_drafts: null
limit_posts: 0
future: false
unpublished: false

# Plugins
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false

# Outputting
permalink: :path/:basename
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Europe/London" # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: mathjax
  syntax_highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


defaults:
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "my-site"
  -
    scope:
      path: "pages"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "project" # overrides previous default layout
      author: "Mr. Hyde"
