name: "Rust CI"
on:
  push:
    branches:
      - "main"
      - "feature/**"
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - "main"
      - "feature/**"
    paths-ignore:
      - "docs/**"
    # Run manually
  workflow_dispatch:
permissions:
  checks: write
jobs:
  rust-ci:
    name: "Format, Lint, Test, and Build"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Format
        uses: actions-rust-lang/rustfmt@v1
      - name: Lint
        uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Test
        run: cargo test --all-features
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
